export default {
  products: [
    {
      _id: "1",
      name: "black t-Shirt",
      category: "Shirts",
      image: "./images/product-1.png",
      price: 600,
      brand: "Hiskywin",
      rating: 1.5,
      numReviews: 36,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "cargo pant",
      category: "Shirts",
      image: "/images/product-2.png",
      price: 500,
      brand: "Hiskywin",
      rating: 4.5,
      numReviews: 106,
      countInStock: 6,
    },
    {
      _id: "3",
      name: "lower",
      category: "pant",
      image: "/images/product-3.png",
      price: 450,
      brand: "Hiskywin",
      rating: 2.5,
      numReviews: 25,
      countInStock: 6,
    },
    {
      _id: "4",
      name: "red t-Shirt",
      category: "t-Shirt",
      image: "/images/product-4.png",
      price: 300,
      brand: "Hiskywin",
      rating: 1.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "5",
      name: "grey color suit",
      category: "pant",
      image: "/images/product-5.png",
      price: 650,
      brand: "Hiskywin",
      rating: 3,
      numReviews: 218,
      countInStock: 6,
    },
    {
      _id: "6",
      name: "white t-Shirt",
      category: "t-shirt",
      image: "/images/product-6.png",
      price: 700,
      brand: "Hiskywin",
      rating: 3.5,
      numReviews: 25,
      countInStock: 6,
    },
  ],
};
